import { existsSync } from "node:fs";
import { access } from "node:fs/promises";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { join, basename, resolve } from "node:path";
import { execSync } from "node:child_process";
import crypto from "node:crypto";
import { readFile } from "node:fs/promises";
import {
  detectBuildDir,
  detectBuildCommand,
  uploadToApi,
  isDeployResult,
  formatBytes,
  formatDeployError,
  createZipBuffer,
  checkImportMapCompleteness,
} from "@deloc/shared";
import { getToken, loadConfig, getApiUrl } from "../config.js";
import { chalk, ora, successBox, errorMessage, warnMessage } from "../ui.js";
import { promptMcpInstall } from "./install-mcp.js";

declare const __PKG_VERSION__: string;

/** Sent as X-Deloc-Client so the API can attribute deploys to the CLI. */
const CLI_CLIENT = `cli/${__PKG_VERSION__}`;

interface DeployOptions {
  name?: string;
  dir?: string;
  noBuild?: boolean;
  password?: string | true;
  public?: boolean;
  domainRestrict?: string; // commander passes comma-separated string
}

function generatePassword(): string {
  return crypto.randomBytes(6).toString("base64url").slice(0, 8);
}

export async function deployCommand(dirArg: string | undefined, options: DeployOptions): Promise<void> {
  // 1. Check auth
  const token = await getToken();
  if (!token) {
    console.log(errorMessage("Not logged in. Run " + chalk.bold("deloc login") + " or " + chalk.bold("deloc register") + " first."));
    process.exit(1);
  }

  const projectDir = resolve(dirArg ?? ".");
  let deployDir: string;

  // 2. Determine deploy directory
  if (options.dir) {
    deployDir = resolve(options.dir);
  } else if (dirArg && existsSync(join(dirArg, "index.html"))) {
    deployDir = resolve(dirArg);
  } else {
    // Auto-detect build output
    const detected = await detectBuildDir(projectDir);
    if (detected) {
      deployDir = detected;
      console.log(chalk.dim(`  Detected build output: ${basename(deployDir)}/`));
    } else if (!options.noBuild) {
      // Try to build first
      const buildCmd = await detectBuildCommand(projectDir);
      if (buildCmd) {
        const spinner = ora("Building project...").start();
        try {
          execSync(buildCmd, { cwd: projectDir, stdio: "pipe" });
          spinner.succeed("Build complete");
        } catch {
          spinner.fail("Build failed");
          console.log(errorMessage("Run the build manually and try again, or use " + chalk.bold("deloc deploy ./dist")));
          process.exit(1);
        }
        const afterBuild = await detectBuildDir(projectDir);
        if (!afterBuild) {
          console.log(errorMessage("Build succeeded but no output directory with index.html found."));
          console.log(chalk.dim("  Specify the directory explicitly: deloc deploy ./dist"));
          process.exit(1);
        }
        deployDir = afterBuild;
      } else {
        // Check if current dir has index.html
        if (existsSync(join(projectDir, "index.html"))) {
          deployDir = projectDir;
        } else {
          console.log(errorMessage("No build output found and no index.html in current directory."));
          console.log(chalk.dim("  Run your build first, or specify the directory: deloc deploy ./dist"));
          process.exit(1);
        }
      }
    } else {
      if (existsSync(join(projectDir, "index.html"))) {
        deployDir = projectDir;
      } else {
        console.log(errorMessage("No index.html found. Specify a build directory."));
        process.exit(1);
      }
    }
  }

  // 3. Validate index.html
  try {
    await access(join(deployDir, "index.html"));
  } catch {
    console.log(errorMessage(`No index.html found in ${deployDir}`));
    process.exit(1);
  }

  // 3b. Check import map completeness
  const html = await readFile(join(deployDir, "index.html"), "utf-8");
  const importMapWarnings = checkImportMapCompleteness(html);
  if (importMapWarnings.length > 0) {
    console.log(warnMessage("Import map issues detected in index.html:"));
    for (const w of importMapWarnings) {
      console.log(chalk.yellow(`  - ${w}`));
    }
    console.log(chalk.dim("  Fix the import map and redeploy. The app may fail to load without these entries."));
    console.log("");
  }

  // 4. Determine app name
  const appName = options.name ?? basename(resolve(projectDir)) ?? "my-app";

  // 5. Handle password
  let password: string | undefined;
  let passwordAutoGenerated = false;
  if (options.password === true) {
    // --password flag with no value: auto-generate
    password = generatePassword();
    passwordAutoGenerated = true;
  } else if (typeof options.password === "string") {
    password = options.password;
  } else if (options.password === undefined && !options.public && !options.domainRestrict) {
    // No --password/--public/--domain-restrict flag: ask the user
    const rl = createInterface({ input: stdin, output: stdout });
    const answer = await rl.question(chalk.bold("Password protect app? (y/N) "));
    rl.close();
    if (answer.trim().toLowerCase() === "y") {
      password = generatePassword();
      passwordAutoGenerated = true;
    }
  }

  // Parse --domain-restrict (comma-separated). Validated client-side for
  // a fast error; API enforces the tier gate regardless.
  let allowedDomains: string[] | undefined;
  if (options.domainRestrict) {
    allowedDomains = options.domainRestrict
      .split(",")
      .map((d) => d.trim().toLowerCase())
      .filter(Boolean);
    if (allowedDomains.length === 0) {
      console.log(errorMessage("--domain-restrict requires at least one domain (e.g. --domain-restrict company.com)"));
      process.exit(1);
    }
  }

  // 6. Zip
  const spinner = ora("Packaging...").start();
  const zipBuffer = await createZipBuffer(deployDir);
  const sizeLabel = formatBytes(zipBuffer.length);
  spinner.text = `Uploading ${sizeLabel}...`;

  // 7. Upload
  const uploadOptions = password
    ? { password }
    : options.public
      ? { visibility: "public" as const }
      : allowedDomains
        ? { visibility: "domain_restricted" as const, allowedDomains }
        : undefined;
  let result;
  try {
    result = await uploadToApi(getApiUrl(), token, zipBuffer, appName, { ...uploadOptions, client: CLI_CLIENT });
  } catch {
    spinner.fail("Could not connect to Deloc API. Check your internet connection.");
    process.exit(1);
  }

  if (!isDeployResult(result)) {
    spinner.fail("Deploy failed");
    console.log(errorMessage(formatDeployError(result.httpStatus, result.error)));
    process.exit(1);
  }

  spinner.stop();

  // 8. Copy to clipboard
  try {
    const { default: clipboardy } = await import("clipboardy");
    await clipboardy.write(result.url);
  } catch {
    // clipboard not available — fine
  }

  // 9. Success output
  console.log("");
  console.log(successBox(result.url, result.slug, result.fileCount, formatBytes(result.totalSizeBytes)));

  if (result.visibility === "domain_restricted" && result.allowedDomains?.length) {
    const domainList = result.allowedDomains.map((d) => `@${d}`).join(", ");
    console.log(`  ${chalk.yellow("●")} ${chalk.bold("Restricted to")} ${chalk.cyan(domainList)}`);
  }

  if (result.visibility === "password_protected" && password) {
    console.log(`  ${chalk.yellow("●")} ${chalk.bold("Password protected")}`);
    console.log(`  ${chalk.dim("Password:")} ${chalk.cyan(password)}`);
    if (passwordAutoGenerated) {
      console.log(chalk.dim("  Share this password with your viewers. It won't be shown again."));
    }
  }

  if (result.expiresAt) {
    const days = Math.ceil((new Date(result.expiresAt).getTime() - Date.now()) / (1000 * 60 * 60 * 24));
    console.log(chalk.dim(`  Free tier: expires in ${days} days. Run ${chalk.bold("deloc renew " + result.slug)} to extend.`));
  }

  if (result.dataFilesDetected && result.dataFilesDetected.length > 0) {
    const sample = result.dataFilesDetected.slice(0, 3).join(", ");
    const more = result.dataFilesDetected.length > 3 ? ` (+${result.dataFilesDetected.length - 3} more)` : "";
    console.log(
      chalk.dim(`  Tip: refresh data without redeploying — ${chalk.bold(`deloc upload-data ${result.slug} <path>`)} (${sample}${more})`),
    );
  }

  console.log("");

  // Offer MCP install on first deploy
  await promptMcpInstall();
}

