import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { writeFile, mkdir } from "node:fs/promises";
import { resolve, join } from "node:path";
import { z } from "zod";
import { requireToken, getToken } from "../api.js";

const text = (t: string) => ({ content: [{ type: "text" as const, text: t }] });

const SOURCES = ["bigquery", "snowflake", "postgres", "mysql", "http"] as const;
type Source = typeof SOURCES[number];

function pythonScript(source: Source, slug: string, query: string): string {
  const imports = sourceImports(source);
  const queryFn = sourceQueryFn(source, query);

  return `#!/usr/bin/env python3
"""
Auto-generated by Deloc. Queries ${source} and pushes results to the
"${slug}" dashboard on Deloc. Schedule with Cloud Scheduler, cron, or
any task runner.

Required env vars:
  DELOC_TOKEN     — API token from deloc.dev/settings/tokens
  DELOC_APP_SLUG  — app slug (default: ${slug})
  DELOC_API_URL   — API base (default: https://api.deloc.dev)
${sourceEnvDocs(source)}
"""
import json
import os

import requests
${imports}

DELOC_API_URL = os.environ.get("DELOC_API_URL", "https://api.deloc.dev")
DELOC_TOKEN = os.environ["DELOC_TOKEN"]
APP_SLUG = os.environ.get("DELOC_APP_SLUG", "${slug}")

${queryFn}

def push_to_deloc(rows: list[dict]) -> None:
    json_bytes = json.dumps(rows, default=str).encode()
    resp = requests.post(
        f"{DELOC_API_URL}/api/apps/{APP_SLUG}/data",
        headers={"Authorization": f"Bearer {DELOC_TOKEN}"},
        files={"file": ("data.json", json_bytes, "application/json")},
    )
    resp.raise_for_status()
    body = resp.json()
    if not body.get("success"):
        raise RuntimeError(f"Deloc upload failed: {body.get('error', 'unknown')}")
    size = body["data"]["files"][0]["size"]
    print(f"Pushed {len(rows)} rows to {APP_SLUG} ({size:,} bytes)")


def main() -> None:
    rows = run_query()
    print(f"Fetched {len(rows)} rows from ${source}")
    push_to_deloc(rows)


if __name__ == "__main__":
    main()
`;
}

function sourceImports(source: Source): string {
  switch (source) {
    case "bigquery":
      return "import google.auth\nfrom google.cloud import bigquery";
    case "snowflake":
      return "import snowflake.connector";
    case "postgres":
      return "import psycopg2\nimport psycopg2.extras";
    case "mysql":
      return "import mysql.connector";
    case "http":
      return "";
  }
}

function sourceEnvDocs(source: Source): string {
  switch (source) {
    case "bigquery":
      return "  GOOGLE_APPLICATION_CREDENTIALS — path to service account JSON key\n  GCP_PROJECT — GCP project ID";
    case "snowflake":
      return "  SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER, SNOWFLAKE_PASSWORD\n  SNOWFLAKE_WAREHOUSE, SNOWFLAKE_DATABASE, SNOWFLAKE_SCHEMA";
    case "postgres":
      return "  DATABASE_URL — postgres://user:pass@host:5432/db";
    case "mysql":
      return "  MYSQL_HOST, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE";
    case "http":
      return "  DATA_SOURCE_URL — URL that returns JSON";
  }
}

function sourceQueryFn(source: Source, query: string): string {
  const escaped = query.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"');

  switch (source) {
    case "bigquery":
      return `GCP_PROJECT = os.environ.get("GCP_PROJECT", "my-project")

QUERY = """
${escaped}
"""


def run_query() -> list[dict]:
    credentials, _ = google.auth.default(
        scopes=["https://www.googleapis.com/auth/bigquery"],
    )
    client = bigquery.Client(project=GCP_PROJECT, credentials=credentials)
    job = client.query(QUERY)
    return [dict(row) for row in job.result()]`;

    case "snowflake":
      return `QUERY = """
${escaped}
"""


def run_query() -> list[dict]:
    conn = snowflake.connector.connect(
        account=os.environ["SNOWFLAKE_ACCOUNT"],
        user=os.environ["SNOWFLAKE_USER"],
        password=os.environ["SNOWFLAKE_PASSWORD"],
        warehouse=os.environ.get("SNOWFLAKE_WAREHOUSE", "COMPUTE_WH"),
        database=os.environ.get("SNOWFLAKE_DATABASE", ""),
        schema=os.environ.get("SNOWFLAKE_SCHEMA", ""),
    )
    try:
        cur = conn.cursor(snowflake.connector.DictCursor)
        cur.execute(QUERY)
        return cur.fetchall()
    finally:
        conn.close()`;

    case "postgres":
      return `QUERY = """
${escaped}
"""


def run_query() -> list[dict]:
    conn = psycopg2.connect(os.environ["DATABASE_URL"])
    try:
        cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        cur.execute(QUERY)
        return [dict(row) for row in cur.fetchall()]
    finally:
        conn.close()`;

    case "mysql":
      return `QUERY = """
${escaped}
"""


def run_query() -> list[dict]:
    conn = mysql.connector.connect(
        host=os.environ["MYSQL_HOST"],
        user=os.environ["MYSQL_USER"],
        password=os.environ["MYSQL_PASSWORD"],
        database=os.environ["MYSQL_DATABASE"],
    )
    try:
        cur = conn.cursor(dictionary=True)
        cur.execute(QUERY)
        return cur.fetchall()
    finally:
        conn.close()`;

    case "http":
      return `DATA_SOURCE_URL = os.environ.get("DATA_SOURCE_URL", "${escaped.trim() || "https://api.example.com/data"}")


def run_query() -> list[dict]:
    resp = requests.get(DATA_SOURCE_URL)
    resp.raise_for_status()
    return resp.json()`;
  }
}

function requirements(source: Source): string {
  const base = "requests>=2.31.0\n";
  switch (source) {
    case "bigquery":
      return base + "google-cloud-bigquery>=3.20.0\n";
    case "snowflake":
      return base + "snowflake-connector-python>=3.6.0\n";
    case "postgres":
      return base + "psycopg2-binary>=2.9.9\n";
    case "mysql":
      return base + "mysql-connector-python>=8.3.0\n";
    case "http":
      return base;
  }
}

function dockerfile(source: Source): string {
  const credLine = source === "bigquery"
    ? "\n# Copy service account key (remove once runtime SA has access)\n# COPY sa-key.json /app/sa-key.json\n# ENV GOOGLE_APPLICATION_CREDENTIALS=/app/sa-key.json\n"
    : "";

  return `FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
${credLine}
# Set DELOC_TOKEN and DELOC_APP_SLUG via env vars (Cloud Run, Secret Manager, etc.)

CMD ["python", "main.py"]
`;
}

function scheduleInstructions(slug: string, source: Source): string {
  return `## How to schedule

### Option A: Cloud Scheduler + Cloud Run Job (GCP)
1. Build and push the container:
   docker build -t gcr.io/YOUR_PROJECT/deloc-refresh-${slug} .
   docker push gcr.io/YOUR_PROJECT/deloc-refresh-${slug}

2. Create a Cloud Run Job:
   gcloud run jobs create deloc-refresh-${slug} \\
     --image gcr.io/YOUR_PROJECT/deloc-refresh-${slug} \\
     --set-env-vars DELOC_TOKEN=dl_xxxxx,DELOC_APP_SLUG=${slug}${source === "bigquery" ? ",GCP_PROJECT=your-project" : ""}

3. Create a Cloud Scheduler trigger:
   gcloud scheduler jobs create http deloc-refresh-${slug}-trigger \\
     --schedule "0 * * * *" \\
     --uri "https://YOUR_REGION-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/YOUR_PROJECT/jobs/deloc-refresh-${slug}:run" \\
     --http-method POST \\
     --oauth-service-account-email YOUR_SA@YOUR_PROJECT.iam.gserviceaccount.com

### Option B: Cron on any server
   # Add to crontab -e:
   0 * * * * cd /path/to/data-refresh && DELOC_TOKEN=dl_xxxxx python main.py >> /var/log/deloc-refresh.log 2>&1

### Option C: GitHub Actions (free, 5 min cron minimum)
   # .github/workflows/refresh-data.yml
   name: Refresh dashboard data
   on:
     schedule:
       - cron: "0 * * * *"
   jobs:
     refresh:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-python@v5
           with: { python-version: "3.12" }
         - run: pip install -r data-refresh/requirements.txt
         - run: python data-refresh/main.py
           env:
             DELOC_TOKEN: \${{ secrets.DELOC_TOKEN }}
             DELOC_APP_SLUG: ${slug}
`;
}

export function registerDataRefreshTool(server: McpServer) {
  return server.tool(
    "setup_data_refresh",
    `Generate a complete backend script that queries a data warehouse and auto-refreshes a Deloc dashboard. Creates a ready-to-deploy Python project (main.py, requirements.txt, Dockerfile) with scheduling instructions.

Supported data sources: BigQuery, Snowflake, Postgres, MySQL, or any HTTP/REST API.

Use this AFTER deploying a dashboard that fetches a data file (e.g. fetch('./data.json')) — this tool generates the pipeline that keeps that file fresh on a schedule.`,
    {
      slug: z.string().describe("The Deloc app slug to push data to"),
      source: z.enum(SOURCES).describe("Data source: bigquery, snowflake, postgres, mysql, or http"),
      query: z.string().optional().describe("SQL query or HTTP URL. Can be left empty to fill in later."),
      output_dir: z.string().optional().describe("Directory to write the generated files (default: ./data-refresh)"),
    },
    async (args) => {
      const token = requireToken();
      if (!token) return text("Error: Not authenticated. Use the setup_deloc tool first.");

      const query = args.query ?? "SELECT * FROM your_table LIMIT 1000";
      const outDir = resolve(process.cwd(), args.output_dir ?? "data-refresh");

      try {
        await mkdir(outDir, { recursive: true });
        await writeFile(join(outDir, "main.py"), pythonScript(args.source, args.slug, query));
        await writeFile(join(outDir, "requirements.txt"), requirements(args.source));
        await writeFile(join(outDir, "Dockerfile"), dockerfile(args.source));
        await writeFile(join(outDir, "README.md"), scheduleInstructions(args.slug, args.source));
      } catch (err) {
        return text(`Error writing files: ${err instanceof Error ? err.message : String(err)}`);
      }

      const delocToken = getToken();
      const tokenSnippet = delocToken ? delocToken.slice(0, 8) + "..." : "dl_xxxxx";

      const lines = [
        `Data refresh backend generated in ${outDir}/`,
        "",
        "Files created:",
        `  main.py          — queries ${args.source}, pushes data.json to ${args.slug}`,
        "  requirements.txt — Python dependencies",
        "  Dockerfile       — ready for Cloud Run / any container runtime",
        "  README.md        — scheduling instructions (Cloud Scheduler, cron, GitHub Actions)",
        "",
        "To test locally:",
        `  cd ${outDir}`,
        "  pip install -r requirements.txt",
        `  DELOC_TOKEN=${tokenSnippet} python main.py`,
        "",
        args.query
          ? "The query is pre-filled. Edit main.py if you need to adjust it."
          : "Open main.py and replace the placeholder SQL query with your actual query.",
        "",
        "See README.md for instructions on scheduling hourly/daily refreshes.",
      ];

      return text(lines.join("\n"));
    },
  );
}
